// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CYChMwEA0RhqSJis95wacM8CPAoYet8',
    appId: '1:979566029457:web:35bb072bd68e78ea442d30',
    messagingSenderId: '979566029457',
    projectId: 'wethaq-270ec',
    authDomain: 'wethaq-270ec.firebaseapp.com',
    storageBucket: 'wethaq-270ec.firebasestorage.app',
    measurementId: 'G-Q697S1ZP3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByWLRahAWku-680Qak3K2a54-ss8_nQlE',
    appId: '1:979566029457:android:ea0f5e02f4f46f55442d30',
    messagingSenderId: '979566029457',
    projectId: 'wethaq-270ec',
    storageBucket: 'wethaq-270ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcZJhsiE4w31e3kKmq-Tym6NpmF4jJzk',
    appId: '1:979566029457:ios:5e26725e38d7fe82442d30',
    messagingSenderId: '979566029457',
    projectId: 'wethaq-270ec',
    storageBucket: 'wethaq-270ec.firebasestorage.app',
    iosBundleId: 'com.example.wethaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlcZJhsiE4w31e3kKmq-Tym6NpmF4jJzk',
    appId: '1:979566029457:ios:5e26725e38d7fe82442d30',
    messagingSenderId: '979566029457',
    projectId: 'wethaq-270ec',
    storageBucket: 'wethaq-270ec.firebasestorage.app',
    iosBundleId: 'com.example.wethaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CYChMwEA0RhqSJis95wacM8CPAoYet8',
    appId: '1:979566029457:web:217b5ed78a0a43ae442d30',
    messagingSenderId: '979566029457',
    projectId: 'wethaq-270ec',
    authDomain: 'wethaq-270ec.firebaseapp.com',
    storageBucket: 'wethaq-270ec.firebasestorage.app',
    measurementId: 'G-JQRVX7W6NW',
  );
}
